#!/bin/bash
# AI Chat to Classroom - Quick Test Guide

echo "🎓 AI Chat to Classroom - Test Guide"
echo "===================================="
echo ""

echo "📋 Pre-Test Checklist:"
echo "  1. ✓ Backend is running"
echo "  2. ✓ iOS Simulator is open"
echo "  3. ✓ App is built and installed"
echo "  4. ✓ User is logged in"
echo ""

echo "🧪 Test Scenarios:"
echo ""
echo "Test 1: Basic Course Creation"
echo "  User Input: 'Create a course on Python'"
echo "  Expected: Chat shows confirmation → Classroom opens → Course generates"
echo ""

echo "Test 2: Course with Level"
echo "  User Input: 'Create a beginner course on Spanish'"
echo "  Expected: Chat shows confirmation → Classroom opens → Course at beginner level"
echo ""

echo "Test 3: Stay in Chat"
echo "  User Input: 'What is a variable in Python?'"
echo "  Expected: Chat shows answer → NO classroom navigation"
echo ""

echo "Test 4: Multi-Topic"
echo "  User Input: 'Create a course on Machine Learning'"
echo "  Then: 'Create another course on Web Development'"
echo "  Expected: Both courses open in sequence"
echo ""

echo "📊 What to Monitor:"
echo ""
echo "Console Logs to Look For:"
echo "  ✅ '🎯 LioChatService Intent: courseCreation'"
echo "  ✅ '🎯 Parsed AI command: OPEN_CLASSROOM'"
echo "  ✅ '🎓 Opening AI Classroom for: [Topic]'"
echo "  ✅ '🎓 Generating course: [Topic] at [level] level'"
echo "  ✅ '✅ Course generated: [Title]'"
echo ""

echo "UI Elements to Check:"
echo "  1. Chat shows AI confirmation message"
echo "  2. CourseGenerationIntermediateView appears with:"
echo "     - Lio avatar animation"
echo "     - Progress bar"
echo "     - Learning objectives preview"
echo "  3. AIGeneratedClassroomView opens with:"
echo "     - Course title"
echo "     - Module/lesson navigation"
echo "     - Content display"
echo ""

echo "🔧 Debugging Tips:"
echo ""
echo "If navigation doesn't trigger:"
echo "  1. Check console for '🎯 Parsed AI command' - if missing, parser failed"
echo "  2. Verify backend returns JSON with 'type: OPEN_CLASSROOM'"
echo "  3. Check AICommandHandler.shouldOpenClassroom is set to true"
echo "  4. Verify LioChatSheet.showingClassroom updates"
echo ""

echo "If course generation fails:"
echo "  1. Check CourseGenerationService.error message"
echo "  2. Verify InteractiveCinemaService is accessible"
echo "  3. Check network connectivity"
echo "  4. Look for backend /api/v1/classroom/chat errors"
echo ""

echo "📝 Testing Checklist:"
echo ""
echo "  [ ] Test 1: Basic course creation works"
echo "  [ ] Test 2: Level detection works"
echo "  [ ] Test 3: Chat stays open for simple questions"
echo "  [ ] Test 4: Multiple courses can be created"
echo "  [ ] Error handling displays properly"
echo "  [ ] Stack item is created"
echo "  [ ] Course opens in classroom"
echo "  [ ] Lessons are navigable"
echo "  [ ] Dismiss returns to chat"
echo ""

echo "✅ Implementation Files Modified:"
echo "  - LyoAIViewModel.swift (AI command detection)"
echo "  - AICommandHandler.swift (Parser fix)"
echo ""

echo "📚 Documentation:"
echo "  See: AI_CHAT_TO_CLASSROOM_IMPLEMENTATION.md"
echo ""

echo "🚀 Ready to test!"
echo ""
echo "To start testing:"
echo "  1. Open Lyo app in simulator"
echo "  2. Tap the Lio orb (3rd tab)"
echo "  3. Type: 'Create a course on Python'"
echo "  4. Watch console logs and UI flow"
echo ""
