import SwiftUI
import os

// MARK: - Draft Model

struct ContentDraft: Identifiable, Codable {
    let id: String
    let mode: String             // CreateMode.rawValue
    let title: String
    let content: String
    let tags: [String]
    var mediaPath: String?       // local file path for media
    let createdAt: Date
    var updatedAt: Date
    
    // Enhancement states
    var hasQuiz: Bool = false
    var hasKeyPoints: Bool = false
    var hasProgressTracker: Bool = false
    var hasResources: Bool = false
    var autoGeneratedTags: [String] = []
    
    // Course-specific
    var courseLevel: String?
    var courseDuration: String?
    var courseCategory: String?
}

// MARK: - Draft Storage Service

/// Persists content drafts to local storage for the Creator flow.
@MainActor
class DraftStorageService: ObservableObject {
    static let shared = DraftStorageService()
    
    @Published var drafts: [ContentDraft] = []
    
    private let storageKey = "lyo_content_drafts"
    private let draftsDirectory: URL
    
    private init() {
        // Create drafts media directory
        let docs = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!
        draftsDirectory = docs.appendingPathComponent("drafts_media", isDirectory: true)
        try? FileManager.default.createDirectory(at: draftsDirectory, withIntermediateDirectories: true)
        
        loadDrafts()
    }
    
    // MARK: - Save Draft
    
    func saveDraft(
        mode: CreateMode,
        title: String,
        content: String,
        tags: [String],
        mediaImage: UIImage? = nil,
        mediaVideoURL: URL? = nil,
        courseLevel: String? = nil,
        courseDuration: String? = nil,
        courseCategory: String? = nil,
        hasQuiz: Bool = false,
        hasKeyPoints: Bool = false,
        hasProgressTracker: Bool = false,
        hasResources: Bool = false,
        autoGeneratedTags: [String] = []
    ) -> ContentDraft {
        var mediaPath: String? = nil
        
        // Save media locally
        if let image = mediaImage {
            let filename = "\(UUID().uuidString).jpg"
            let filePath = draftsDirectory.appendingPathComponent(filename)
            if let data = image.jpegData(compressionQuality: 0.7) {
                try? data.write(to: filePath)
                mediaPath = filePath.path
            }
        } else if let videoURL = mediaVideoURL {
            let filename = "\(UUID().uuidString).mp4"
            let destPath = draftsDirectory.appendingPathComponent(filename)
            try? FileManager.default.copyItem(at: videoURL, to: destPath)
            mediaPath = destPath.path
        }
        
        let draft = ContentDraft(
            id: UUID().uuidString,
            mode: mode.rawValue,
            title: title,
            content: content,
            tags: tags,
            mediaPath: mediaPath,
            createdAt: Date(),
            updatedAt: Date(),
            hasQuiz: hasQuiz,
            hasKeyPoints: hasKeyPoints,
            hasProgressTracker: hasProgressTracker,
            hasResources: hasResources,
            autoGeneratedTags: autoGeneratedTags,
            courseLevel: courseLevel,
            courseDuration: courseDuration,
            courseCategory: courseCategory
        )
        
        drafts.insert(draft, at: 0)
        persistDrafts()
        
        Log.ui.info("📝 Draft saved: \(title) (\(mode.rawValue))")
        return draft
    }
    
    // MARK: - Delete Draft
    
    func deleteDraft(_ draft: ContentDraft) {
        // Remove media file
        if let path = draft.mediaPath {
            try? FileManager.default.removeItem(atPath: path)
        }
        
        drafts.removeAll { $0.id == draft.id }
        persistDrafts()
    }
    
    // MARK: - Load Draft into Editor
    
    func getDrafts(for mode: CreateMode) -> [ContentDraft] {
        return drafts.filter { $0.mode == mode.rawValue }
    }
    
    // MARK: - Persistence
    
    private func persistDrafts() {
        if let data = try? JSONEncoder().encode(drafts) {
            UserDefaults.standard.set(data, forKey: storageKey)
        }
    }
    
    private func loadDrafts() {
        if let data = UserDefaults.standard.data(forKey: storageKey),
           let decoded = try? JSONDecoder().decode([ContentDraft].self, from: data) {
            drafts = decoded
        }
    }
    
    // MARK: - Auto-Generate Tags
    
    /// Generate tags from content text using simple keyword extraction.
    static func generateTags(from title: String, content: String) -> [String] {
        let combined = "\(title) \(content)".lowercased()
        
        let educationKeywords: [(String, String)] = [
            ("math", "#math"),
            ("calculus", "#calculus"),
            ("algebra", "#algebra"),
            ("physics", "#physics"),
            ("chemistry", "#chemistry"),
            ("biology", "#biology"),
            ("history", "#history"),
            ("english", "#english"),
            ("programming", "#programming"),
            ("coding", "#coding"),
            ("science", "#science"),
            ("tutorial", "#tutorial"),
            ("learn", "#learning"),
            ("study", "#study"),
            ("exam", "#examprep"),
            ("tips", "#tips"),
            ("homework", "#homework"),
            ("research", "#research"),
        ]
        
        var tags: [String] = []
        for (keyword, tag) in educationKeywords {
            if combined.contains(keyword) && !tags.contains(tag) {
                tags.append(tag)
            }
        }
        
        // Always add a generic education tag
        if tags.isEmpty {
            tags.append("#education")
        }
        
        // Cap at 5 tags
        return Array(tags.prefix(5))
    }
}
